### ISSUE TITLE
Error doing job: Exception in callback Entity.async_write_ha_state()

### ISSUE THREAD

**Issue by AlexW75** [tschamm/boschshc-hass#109]
Hello,

I have the following error in my log. It occurs about 2 times per day.
Currently I have no way to reproduce it on purpose.
It seems to have no negative effect to the system.

If there is additional info needed just let me know - I will provide.

Logger: homeassistant
Source: custom_components/bosch_shc/switch.py:379 
Integration: Bosch SHC ([documentation](https://github.com/tschamm/boschshc-hass/blob/master/README.md), [issues](https://github.com/tschamm/boschshc-hass/issues)) 
First occurred: 16:19:41 (3 occurrences) 
Last logged: 19:27:23

Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1238, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bosch_shc/switch.py", line 379, in is_on
    getattr(self._device, self.entity_description.on_key)
  File "/usr/local/lib/python3.11/site-packages/boschshcpy/models_impl.py", line 478, in bypass
    return self._bypass_service.value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/boschshcpy/services_impl.py", line 237, in value
    return self.State(self.state["state"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 'UNKNOWN' is not a valid BypassService.State

**Comment by tschamm** [comment]
Thanks for reporting. I‘ll look into it

**Comment by tschamm** [comment]
will be fixed with the next update of boschshcpy

**Comment by AlexW75** [comment]
Thank you very much!!Great integration.AlexanderAm 26.09.2023 um 22:19 schrieb Thomas Schamm ***@***.***>:﻿
will be fixed with the next update of boschshcpy
