### ISSUE TITLE
micromodule_relay devices no longer available

### ISSUE THREAD

**Issue by hkohls** [tschamm/boschshc-hass#113]
Since appr. 5 days my devices of type micromodule_relay are disconnected. After deleting and reconfiguring the bosch integration no micromodule_relay devices are found anymore. The devices are still visible and working fine with Bosch app

**Comment by tschamm** [comment]
Are they configured as impulse switches or as normal switches? The implementation for impulse switches is not fully done.

**Comment by hkohls** [comment]
As regular switch, and they worked before with your integration.

**Comment by tschamm** [comment]
Can you check the logs when restarting HA, if there are error messages from either boschshc_hass or boschshcpy popping up? I guess I screwed it up when implementing the Impulse switch.

**Comment by COLT9001** [comment]
2023-10-03 16:15:18.160 ERROR (MainThread) [homeassistant.components.switch] Error while setting up bosch_shc platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/bosch_shc/switch.py", line 223, in async_setup_entry
for switch in session.device_helper.micromodule_relays:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/boschshcpy/device_helper.py", line 121, in micromodule_relays
devices.extend(relay)
TypeError: 'SHCMicromoduleRelay' object is not iterable

**Comment by hkohls** [comment]
Since I restored my last Backup, I lost  all trace. Hope the above log from colt9001 is good enough! Thanks for investigating on this!

**Comment by tschamm** [comment]
Thanks, I fixed it with [b7cdcea](https://github.com/tschamm/boschshc-hass/commit/b7cdceadd018e0da8134aa0362c52dce8f5434a7)

**Comment by hkohls** [comment]
Can we please open this issue again? I still run into the same problem of deactivated switches, using you latest releases.
I wonder if this here might be the cause. You validate the profile for "GENERIC" and set the type of relay. But the device scanner shows this setting in both configurations.  The indicators are "PowerSwitch" or " "ImpulseSwitch""


Your code in models_impl.py
return (
            self.RelayType.BUTTON
            if self.profile == "GENERIC"
            else self.RelayType.SWITCH
        )

Extract from scan:
"id": "hdm:ZigBee:287681fffe7083c5",
        "deviceServiceIds": [
            "CommunicationQuality",
            "PowerSwitch",
            "ChildProtection",
            "PowerSwitchProgram",
            "ElectricalFaults",
            "SwitchConfiguration"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_1",
        "deviceModel": "MICROMODULE_RELAY",
        "serial": "287681FFFE7083C5",

**Comment by tschamm** [comment]
For sure. Checking the service would be ok also, but at least I assumed the profile type is giving hint enough.
Maybe at some point I have to buy a relay to test.

**Comment by tschamm** [comment]
Problem is still existing?

**Comment by danielpetrovic** [comment]
Sorry, I have removed the Bosch SHC II and just connected the Relay to Z2M which works fine. ZHA also works for people using that.

**Comment by hkohls** [comment]
I updated to your latest version which fixed the impulse switch. But I see **this** problem again. In October I just reverted to an older version to get rid of it.

**Comment by tschamm** [comment]
Ok, do you see an error message in the logs? Related to one of the Platforms?

**Comment by hkohls** [comment]
Please advice: where do I find the log?

**Comment by hkohls** [comment]
I managed to get access to the logs, changed the loglevel for custom_components.bosch_shc to debug and reloaded the integration: no erros! Any other procedures to follow that might give you hints?

**Comment by hkohls** [comment]
I reinstalled everything. Same error, but now with log:
2024-02-04 16:47:03.546 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547969557824] 'NoneType' object has no attribute 'put_state_element'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 147, in async_press
    await self.hass.async_add_executor_job(self.press)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/button.py", line 82, in press
    self._device.trigger_impulse_state()
  File "/usr/local/lib/python3.11/site-packages/boschshcpy/models_impl.py", line 271, in trigger_impulse_state
    self._impulseswitch_service.put_state_element("impulseState", True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'put_state_element'

**Comment by hkohls** [comment]
Seems the switches are identified as impulse:
![image](https://github.com/tschamm/boschshc-hass/assets/52618842/20496830-e12d-406e-b531-cdd2cd13f841)

**Comment by hkohls** [comment]
Please have a look at the output from the device scan I did last year. All share the profile GENERIC, but they differ in this setting:
![image](https://github.com/tschamm/boschshc-hass/assets/52618842/9a8d6662-4cb1-4697-ad2d-b7df710d5524)
![image](https://github.com/tschamm/boschshc-hass/assets/52618842/00a437d0-7721-474a-84d1-073d699b5ab8)

**Comment by tt-pete** [comment]
Mit der neuen Version 0.4.85 funktioniert es auch bei mir als Schalter weiterhin nicht. Error-Meldungen ähnlich wie oben: 

2024-02-11 21:47:26.822 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140208032504256] 'NoneType' object has no attribute 'put_state_element'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/button/init.py", line 139, in _async_press_action
await self.async_press()
File "/usr/src/homeassistant/homeassistant/components/button/init.py", line 154, in async_press
await self.hass.async_add_executor_job(self.press)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bosch_shc/button.py", line 82, in press
self._device.trigger_impulse_state()
File "/usr/local/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 271, in trigger_impulse_state
self._impulseswitch_service.put_state_element("impulseState", True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'put_state_element'

**Comment by MarkusHaag** [comment]
I experience the same issue. In the past I configured them as switches to expose them in Homekit (setup without HomeAssistant) and to mimik Button I had automatization to switch them off once switched on. 
If I got it right, they would be functional in HomeAssistant when configured as button. As I am anyhow changing my setup to HomeAssistant this could be my solution to simple reconfigure them correctly or do I miss something?

**Comment by tt-pete** [comment]
I have now removed and re-added the relay several times in the Bosch app, but I still get the above error.  

In the Bosch app, the relay is displayed as follows: 

![Screenshot_2024-02-17-10-22-15-792_com bosch sh ui android](https://github.com/tschamm/boschshc-hass/assets/141581298/1ebf9cdb-3cc2-4bf1-a9a7-005c825201d4)

I get always the error "NoneType' object has no attribute 'put_state_element" when I press the button in Home Assistant.

**Comment by DrPain911** [comment]
Habe this Problem as well with the latest version. Will try readding it into the shc.

**Comment by DrPain911** [comment]
Hallo back, I just tried removing and readding the devices. Is there something I can do to help get this solved?

**Comment by tschamm** [comment]
Version 0.4.91 has checks if the services of the relays are NoneType. Should fix the error ```AttributeError: 'NoneType' object has no attribute 'put_state_element'```. Can you please re-check.

**Comment by DrPain911** [comment]
Thanks! So the error does not appear anymore, but unfortunately pressing the button does not change the state of the device.

**Comment by tschamm** [comment]
That was what I feared. Do you know from the API, what would be the command to trigger the device?

**Comment by DrPain911** [comment]
Unfortunately not, as I’m not too familiar with these kinds of things. My workaround involved connecting to the BSH with HA via HomeKit to get the functionality back. I would prefer your Integration though as it enables much more functionality 👍🏻

**Comment by tt-pete** [comment]
I also see the button now.  But pressing it, doesn't cause any switching. 

I don't have any knowledge of the API either. However, I already wrote in my post from February 13, 2024 that it worked until version 0.4.57. A subsequent change resulted in the error. Maybe this information will help to find a solution.

**Comment by webfal** [comment]
> That was what I feared. Do you know from the API, what would be the command to trigger the device?

The MICROMODULE_RELAY be switch on/off like a PowerSwitch.
It's the PUT request
   {{shc_api}}/devices/{{device_id}}/services/PowerSwitch/state
with the body
  {"@type": "powerSwitchState","switchState": "[OFF or ON]"}

**Comment by RkcCorian** [comment]
I checked shortly with the Adapter in ioBroker and there it is working fine. So this not a limitation of the Bosch API, it must be related to the integration in Home Assistant.

**Comment by tschamm** [comment]
So I bought myself a relais to test the issue. After some first tests, it seems the device is providing different services depending on its initial configuration as an impulse controller or an on/off switch.

<img src="https://github.com/user-attachments/assets/9e4cb87b-9509-4a4d-9f5b-d792abde93fd" width=30% height=30%>

The initial configuration however cannot be resolved afterwards, so I assume we need to guess whether it's configured as the one or the other. I try to provide a fix in the boschshcpy library supporting both configurations.

**Comment by RkcCorian** [comment]
@tschamm : Nice, many thanks!! When would it be available in HACS officially? I would test and of course also send some money once working as you also invested money for the relais for us.

**Comment by tschamm** [comment]
Pre-Release is already available in HACS, maybe you need to look directly in the HACS entry for the Pre-Release version.

**Comment by RkcCorian** [comment]
@tschamm : Es funktioniert, vielen Dank!! Keine Ahnung wie ich Dir nen Kaffee ausgeben kann... 🙈

**Comment by RkcCorian** [comment]
@tschamm: So, hab gefunden, wie ich nen Kaffee spenden kann :-)

Beside this one hint: with the ```0.4.96-dev6``` it is not possible to change the temperature...
![image](https://github.com/user-attachments/assets/190acf83-90aa-48aa-b5ea-25c6c5ac72f5)
I did not created an issue as I found this in a dev version, not sure about the productive, hope this is fine.

**Comment by tschamm** [comment]
Thanks for reporting, I need to take a look as there has been one change in the climate platform.
