### ISSUE TITLE
Float values to climate.set_temperature that are not quantized to steps of .5 will raise API error

### ISSUE THREAD

**Issue by basslet** [tschamm/boschshc-hass#115]
Issue: API call returned non-OK result (code 400) when using climate.set_temperature with Bosch thermostats:

2023-10-17 11:22:36.750 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: SHC Error (message: API call returned non-OK result (code 400)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"INVALID_REQUEST_OBJECT","statusCode":400}')
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
response_data = await self._async_run_long_action(

Reproduce:
Go to Developer Tools > Services
Select Climate: Set temperature
Select a Bosch SHC target thermostat
Set temperature to 18
Call service -> Ok result

Set temperature to 18.1 -> API call returned non-OK result (code 400)
Set temperature to 18.5 -> Ok result

Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

SHC 0.4.63

(This problem has been [bugging me for a few months](https://github.com/tschamm/boschshc-hass/issues/91), so unrelated to the current HA version)

Workaround: Quantize float values to steps of .5

[log.txt](https://github.com/tschamm/boschshc-hass/files/12926957/log.txt)

**Comment by tschamm** [comment]
Basically this is only a problem when calling the service to set the temperature, as the climate card is using the step sizes. I anyhow fixed it, hope it helps.
