### ISSUE TITLE
Bosch Outdoor Siren 

### ISSUE THREAD

**Issue by n0x31x** [tschamm/boschshc-hass#120]
Hi !

Would it be possible to Support the Bosch Outdoor Siren? If you need any help, please let me know !

Thanks ans regards!

**Comment by tschamm** [comment]
I don't own that one. If you can provide the [rawscan](https://github.com/tschamm/boschshcpy#rawscans), I can try to add support.

**Comment by n0x31x** [comment]
Hi Tschamm

Kenne mich leider nicht so gut damit aus. Woher bekomme ich das nötige Zertifikat? Notfalls kann ich dir die sirene auch zuschicken? :)

**Comment by tschamm** [comment]
Das ist in Abschnitt [CLI access to SHC](https://github.com/tschamm/boschshcpy#command-line-access-to-shc) erklärt. Allerdings brauchst du dafür ein System mit Python >=3.10. 

Wenn du das nicht verfügbar hast, kannst du auch den integrierten Dienst in Home Assistant nutzen:
Entwicklerwerkzeuge -> Dienste -> "Bosch SHC: Rawscan auslösen", Rawscan Befehl `devices` (falls du die Device ID noch nicht kennst), ansonsten `device_services` mit der device_id.
Du findest die Informationen dann im Home Assistant Log: Einstellungen -> System -> Protokolle. 
Melde dich gerne nochmals, wenn du Fragen hast.

**Comment by n0x31x** [comment]
Klappt nicht wirklich über HA, bekomme errors, dabei macht es keinen unterschied ob device oder device_services mit der device_id. Werde das noch mit dem lokalen python probieren, dafür müsste ich mir erstmal ein cert erstellen.

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: SHC Error (message: API call returned non-OK result (code 404)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"ENTITY_NOT_FOUND","statusCode":404}')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/__init__.py", line 203, in rawscan_service_call
    rawscan = await hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/boschshcpy/session.py", line 389, in rawscan
    return self._api.get_device_services(device_id=kwargs["device_id"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/boschshcpy/api.py", line 176, in get_device_services
    return self._get_api_result_or_fail(api_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/boschshcpy/api.py", line 80, in _get_api_result_or_fail
    self._process_nok_result(result)
  File "/usr/local/lib/python3.11/site-packages/boschshcpy/api.py", line 123, in _process_nok_result
    raise SHCSessionError(
boschshcpy.exceptions.SHCSessionError: SHC Error (message: API call returned non-OK result (code 404)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"ENTITY_NOT_FOUND","statusCode":404}')

**Comment by tschamm** [comment]
Das Key/Cert Paar erstellen geht auch über das Command Line Interface:
```
boschshc_registerclient -ip _your_shc_ip_ -pw _your_shc_password_
```

**Comment by n0x31x** [comment]
endlich hinbekommen , vielen Dank für deine Hilfe, auszug aus dem rawscan:

  {
        "@type": "device",
        "rootDeviceId": "64-da-a0-40-0e-XX",
        "id": "hdm:ZigBee:385b44fffeabdeca",
        "deviceServiceIds": [
            "CommunicationQuality",
            "BatteryLevel",
            "OutdoorSiren",
            "LegacyAlarmConfiguration",
            "OutdoorSirenPowerSupply"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_2",
        "deviceModel": "OUTDOOR_SIREN",
        "serial": "XXXXXXXXXX",
        "profile": "GENERIC",
        "name": "Au\u00dfensirene",
        "status": "UNDEFINED",
        "childDeviceIds": [],
        "supportedProfiles": []

**Comment by tschamm** [comment]
Super, kannst du bitte noch die Services schicken?

**Comment by n0x31x** [comment]
bitte sehr: 

{
        "@type": "DeviceServiceData",
        "id": "OutdoorSiren",
        "deviceId": "hdm:ZigBee:385b44fffeaxxxx",
        "operations": [
            "triggerTestAlarm",
            "muteWarning"
        ],
        "path": "/devices/hdm:ZigBee:385b44fffeaxxxx/services/OutdoorSiren"
    },
    {
        "@type": "DeviceServiceData",
        "id": "BatteryLevel",
        "deviceId": "hdm:ZigBee:385b44fffeaxxxx",
        "path": "/devices/hdm:ZigBee:385b44fffeaxxxx/services/BatteryLevel"
    },
    {
        "@type": "DeviceServiceData",
        "id": "CommunicationQuality",
        "deviceId": "hdm:ZigBee:385b44fffeaxxxx",
        "state": {
            "@type": "communicationQualityState",
            "quality": "UNKNOWN"
        },
        "path": "/devices/hdm:ZigBee:385b44fffeaxxxx/services/CommunicationQuality"
    },
    {
        "@type": "DeviceServiceData",
        "id": "OutdoorSirenPowerSupply",
        "deviceId": "hdm:ZigBee:385b44fffeaxxxx",
        "state": {
            "@type": "powerSupplyState",
            "configuredPowerSupply": "UNKNOWN"
        },
        "path": "/devices/hdm:ZigBee:385b44fffeaxxxx/services/OutdoorSirenPowerSupply"
    },
    {
        "@type": "DeviceServiceData",
        "id": "LegacyAlarmConfiguration",
        "deviceId": "hdm:ZigBee:385b44fffeaxxxx",
        "state": {
            "@type": "legacyAlarmConfiguration",
            "profileToActivate": "1",
            "triggerSmartAlarmSystemEnabled": true,
            "overrideDisarmedSmartAlarmSystemEnabled": true
        },
        "path": "/devices/hdm:ZigBee:385b44fffeaxxxx/services/LegacyAlarmConfiguration"
    }

**Comment by n0x31x** [comment]
Wie stehen die Chancen, dass es klappen wird? :)

**Comment by n0x31x** [comment]
Thank you, if there is anything I can help, please let me know

**Comment by dondomon82** [comment]
I would also love the integration of the outdoor siren. Greetings

**Comment by mosandlt** [comment]
The Outdoor Siren is implementable — the Bosch `OutdoorSiren` API spec is available and a rawscan was shared — but none of the maintainers own the device, so we'd need someone with the siren to test (alarm/tamper/battery entities + test/mute buttons). It's on the device roadmap; leaving open and looking for a tester.

**Comment by mosandlt** [comment]
I've captured the full `OutdoorSiren` / `OutdoorSirenPowerSupply` service surface from the rawscans in our internal device DB, so the API side is understood. The blocker is that none of the maintainers own an Outdoor Siren to validate the alarm/mute write path safely. Leaving open as a feature backlog item — a tester with the device (and a willingness to verify on a real siren) would unblock it.

**Comment by mosandlt** [comment]
Initial **Outdoor Siren** support shipped in **0.7.11** (+ boschshcpy 0.3.10): acoustic/visual/tamper binary_sensors, battery/power-source/solar-charging diagnostic sensors, alarm & flash duration/delay number config, a sound-level select, and a **Test Alarm** button. This is spec-grounded (Bosch local OpenAPI) but I don't have the hardware to live-test — if you can update and report what entities appear (and whether the Test Alarm button works), that would be a big help before I close this.

**Comment by COLT9001** [comment]
When i press the "Alarm Button" i got an error

Failed to perform the action button/press. SHC Error (message: API call returned non-OK result (code 422)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"JSON_MAPPING_FAILED","statusCode":422}')

The other entries look good. When I change the parameters, they're transferred correctly as well.
One more tip regarding the threshold values

Alarm delay: 0–60 seconds
Alarm duration: 1–15 minutes

<img width="311" height="1181" alt="Image" src="https://github.com/user-attachments/assets/58da00cd-355f-4f97-a45d-95e7adb05998" />

**Comment by mosandlt** [comment]
Thanks for the report and the threshold tips!

The 422 \`JSON_MAPPING_FAILED\` means the SHC rejected our JSON body. We're currently sending \`{"soundLevel": "LOW"}\` per the Bosch OpenAPI spec, but the SHC's internal Jackson deserializer likely requires an \`@type\` discriminator field that the spec omitted.

Before we ship a fix, could you help narrow it down?

**Option A — enable debug logging in HA:**
Developer Tools → YAML → Services → \`logger: set_level\` → \`{boschshcpy: debug}\`, press the button again, then share the relevant lines from Settings → System → Logs.

**Option B — quick curl test** (if you still have the client cert from the rawscan):
```bash
curl -X POST "https://{shc_ip}:8444/smarthome/devices/{device_id}/services/OutdoorSiren/operation/triggerTestAlarm" \
  --cert client-cert.pem --key client-key.pem --insecure \
  -H "api-version: 3.2" -H "Content-Type: application/json" \
  -d 'null'
```
If that returns 204, the fix is to send no body at all (the SHC fires at its configured sound level). If still 422, we'd need to try with `@type`.

Also: the threshold limits you mentioned (**alarm delay 0–60 s, alarm duration 1–15 min**) are helpful — I'll tighten the number entity ranges to enforce those bounds. Thanks!

**Comment by mosandlt** [comment]
Found it — traced this through a decompile of the official Bosch Android app.

The SHC's `operation/{name}` endpoints (this includes `triggerTestAlarm`) don't take a named JSON object at all — the app's generic operation-trigger mechanism (`DeviceService.executeOperation(name, listener, Object[] params)`) passes its params straight into Jackson's serializer with **no wrapping**. For a call like `executeOperation("triggerTestAlarm", listener, new Object[]{"LOW"})`, that means the real wire body is a **bare JSON array**: `["LOW"]` — not `{"soundLevel": "LOW"}`, which is what we send today (and what the official OpenAPI spec says to send — the spec is wrong here, same as the alarm/flash-duration unit mismatch we found earlier on this same device).

I've implemented the fix in `boschshcpy` (sends `["LOW"]`/`["MEDIUM"]`/`["HIGH"]` instead of the object), but since none of us own this hardware, I don't want to ship another guess without confirming it against a real siren first — this bug already had one round of "spec says X, siren rejects X."

@COLT9001 (or anyone else with the device) — could you try this against your SHC before we release?

```bash
curl -X POST "https://{shc_ip}:8444/smarthome/devices/{device_id}/services/OutdoorSiren/operation/triggerTestAlarm" \
  --cert client-cert.pem --key client-key.pem --insecure \
  -H "api-version: 3.2" -H "Content-Type: application/json" \
  -d '["LOW"]'
```

(swap `{shc_ip}`/`{device_id}` for yours, and the cert/key from your rawscan setup). A `204` means this is the fix — a repeat `422` means I'm still missing something and I'll dig further. Thanks again for the earlier threshold tips, those are queued up too once this part is confirmed.

**Comment by COLT9001** [comment]
Hi, yes i can test. 
Unfortunately, I forgot to reply to the request regarding the debugging. I have a lot on my plate right now...

Am 7. Juli 2026 11:18:31 UTC schrieb Thomas ***@***.***>:
>mosandlt left a comment (tschamm/boschshc-hass#120)
>
>Found it — traced this through a decompile of the official Bosch Android app.
>
>The SHC's `operation/{name}` endpoints (this includes `triggerTestAlarm`) don't take a named JSON object at all — the app's generic operation-trigger mechanism (`DeviceService.executeOperation(name, listener, Object[] params)`) passes its params straight into Jackson's serializer with **no wrapping**. For a call like `executeOperation("triggerTestAlarm", listener, new Object[]{"LOW"})`, that means the real wire body is a **bare JSON array**: `["LOW"]` — not `{"soundLevel": "LOW"}`, which is what we send today (and what the official OpenAPI spec says to send — the spec is wrong here, same as the alarm/flash-duration unit mismatch we found earlier on this same device).
>
>I've implemented the fix in `boschshcpy` (sends `["LOW"]`/`["MEDIUM"]`/`["HIGH"]` instead of the object), but since none of us own this hardware, I don't want to ship another guess without confirming it against a real siren first — this bug already had one round of "spec says X, siren rejects X."
>
>@COLT9001 (or anyone else with the device) — could you try this against your SHC before we release?
>
>```bash
>curl -X POST "https://{shc_ip}:8444/smarthome/devices/{device_id}/services/OutdoorSiren/operation/triggerTestAlarm" \
>  --cert client-cert.pem --key client-key.pem --insecure \
>  -H "api-version: 3.2" -H "Content-Type: application/json" \
>  -d '["LOW"]'
>```
>
>(swap `{shc_ip}`/`{device_id}` for yours, and the cert/key from your rawscan setup). A `204` means this is the fix — a repeat `422` means I'm still missing something and I'll dig further. Thanks again for the earlier threshold tips, those are queued up too once this part is confirmed.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/tschamm/boschshc-hass/issues/120#issuecomment-4903177860
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
