### ISSUE TITLE
Setup failed for custom integration bosch_shc: Unable to import component: Exception importing custom_components.bosch_shc

### ISSUE THREAD

**Issue by cvergie77** [tschamm/boschshc-hass#154]
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 10:21:58 (1 occurrences)
Last logged: 10:21:58

Setup failed for custom integration bosch_shc: Unable to import component: Exception importing custom_components.bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bosch_shc/__init__.py", line 56, in <module>
    Platform.VALVE,
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: VALVE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 824, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.bosch_shc

**Comment by tschamm** [comment]
You need to update HA to 2024.1.0 or later. Platform Valve was introduced only recently
