### ISSUE TITLE
Integration cannot be loaded since HA 2024.2.0

### ISSUE THREAD

**Issue by PhilR001** [tschamm/boschshc-hass#164]
Since HA Version 2024.2.0, the Integration cannot be loaded any more.

Thanks for helping...

Failure message is:

The following integrations and platforms could not loaded:

Bosch-shc

‐----

Log shows:

Logger: homeassistant.config_entries
Source: config_entries.py:2275
First occurred: 07:34:00 (1 occurrences)
Last logged: 07:34:00

Error occurred loading flow for integration bosch_shc: Exception importing custom_components.bosch_shc.config_flow

----------

Logger: homeassistant.loader
Source: loader.py:847
First occurred: 07:34:00 (1 occurrences)
Last logged: 07:34:00

Unexpected exception importing platform custom_components.bosch_shc.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch_shc/__init__.py", line 5, in <module>
    from boschshcpy import SHCSession, SHCUniversalSwitch
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/__init__.py", line 1, in <module>
    from .device import SHCDevice
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/device.py", line 4, in <module>
    from .device_service import SHCDeviceService
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/device_service.py", line 3, in <module>
    from .api import SHCAPI
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/api.py", line 4, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

**Comment by PhilR001** [comment]
Is there any easy solution to fix this?

The integration is great, however, I still can't use it

**Comment by tschamm** [comment]
Fixed with the current release
