### ISSUE TITLE
Bosch shc still not working since HA 2024.2

### ISSUE THREAD

**Issue by PhilR001** [tschamm/boschshc-hass#166]
Compare issue#161:

I installed the current version of bosch Integration, v0.4.87.

Unfortunately, Bosch Integration still cannot be opened.

Also reinstall and multiple HA restarts did not work.

HA logs below

**Comment by PhilR001** [comment]
Invalid config
The following integrations and platforms could not be set up:

[bosch_shc](https://github.com/tschamm/boschshc-hass/blob/master/README.md) ([Show logs](https://philipprettenmeier.duckdns.org:8123/config/logs?filter=bosch_shc))
Please check your config and [logs](https://philipprettenmeier.duckdns.org:8123/config/logs).

Vor 2 Minuten

**Comment by PhilR001** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:2275
First occurred: 11:01:33 (1 occurrences)
Last logged: 11:01:33

Error occurred loading flow for integration bosch_shc: Exception importing custom_components.bosch_shc.config_flow

**Comment by PhilR001** [comment]
Logger: homeassistant.loader
Source: loader.py:847
First occurred: 11:01:33 (1 occurrences)
Last logged: 11:01:33

Unexpected exception importing platform custom_components.bosch_shc.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch_shc/__init__.py", line 5, in <module>
    from boschshcpy import SHCSession, SHCUniversalSwitch
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/__init__.py", line 37, in <module>
    from .register_client import SHCRegisterClient
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/register_client.py", line 7, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

**Comment by PhilR001** [comment]
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 11:01:14 (1 occurrences)
Last logged: 11:01:14

Setup failed for custom integration 'bosch_shc': Unable to import component: Exception importing custom_components.bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch_shc/__init__.py", line 5, in <module>
    from boschshcpy import SHCSession, SHCUniversalSwitch
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/__init__.py", line 37, in <module>
    from .register_client import SHCRegisterClient
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/register_client.py", line 7, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 835, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.bosch_shc

**Comment by PhilR001** [comment]
Logger: homeassistant.loader
Source: loader.py:827
First occurred: 11:01:14 (1 occurrences)
Last logged: 11:01:14

Unexpected exception importing component custom_components.bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch_shc/__init__.py", line 5, in <module>
    from boschshcpy import SHCSession, SHCUniversalSwitch
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/__init__.py", line 37, in <module>
    from .register_client import SHCRegisterClient
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/register_client.py", line 7, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

**Comment by tschamm** [comment]
I removed the dependency on pkg_resources now. Can you test 0.4.88?

**Comment by PhilR001** [comment]
Yes, it works!!!

Great, thank you a lot

**Comment by PhilR001** [comment]
Coffee is donated ;)
