### ISSUE TITLE
No complaints, just noticed these errors in the logs. Close case if desired immiadetely.

### ISSUE THREAD

**Issue by HAuser2019** [tschamm/boschshc-hass#167]
i noticed these errors in the logs:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bosch_shc/sensor.py:371
Integration: Bosch SHC (documentation, issues)
First occurred: February 24, 2024 at 23:40:04 (1 occurrences)
Last logged: February 24, 2024 at 23:40:04

Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 549, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/sensor.py", line 371, in native_value
    return self._device.communicationquality.name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 35, in communicationquality
    return self._communicationquality_service.value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/services_impl.py", line 802, in value
    return self.State(self.state["quality"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'FETCHING' is not a valid CommunicationQualityService.State
```

```
Logger: boschshcpy
Source: /usr/local/lib/python3.12/site-packages/boschshcpy/session.py:151
First occurred: 17:32:20 (1 occurrences)
Last logged: 17:32:20

SHC claims unknown poll id. Invalidating poll id and trying resubscribe next time...
```

```
Logger: boschshcpy
Source: /usr/local/lib/python3.12/site-packages/boschshcpy/session.py:240
First occurred: 17:32:20 (1 occurrences)
Last logged: 17:32:20

_long_poll returned False. Waiting 1 second.
```

I'd like the use the "official integration" instead of HACS. Is the official one yet up to date with the Smoke detector II, motion sensor and alarm funcions?

**Comment by HuisAutomatisering** [comment]
Hey the difference with the official integration is:
-Your motion sensor won't work (shows only battery)
-Your Presence simulation service won't work
-Your Smoke detection of the Twinguard won't work
-Your Intrusion detection system won't work.
-Your doorsensors won't have the vibration detection.
-Your Smoke detector II will only show battery...
That's in my case, so quite a lot... also wish the official intergration would have these working :-) Then I could disable the use of HACS.

**Comment by mosandlt** [comment]
Addressed by the thread-safety fixes in #300 (the daily cert-check is async; sensors cache the device id instead of `run_coroutine_threadsafe().result()`). Please verify after updating. Released in [v0.4.104](https://github.com/tschamm/boschshc-hass/releases/tag/v0.4.104) — OK to close once you've updated? Please reopen/comment if it persists.

**Comment by mosandlt** [comment]
Fixed in **boschshc-hass 0.4.104** — the off-loop callback / thread-safety errors were fixed.

Please update (via HACS, or manually — see #279) and restart Home Assistant. If you're on ≥0.4.104 and still hit this, comment here and we'll dig back in; otherwise I'll close this in ~2 weeks. Thanks!

**Comment by mosandlt** [comment]
This whole class of "called from a thread other than the event loop" / off-loop callback errors was fixed: first by marshalling the SHC polling-thread callbacks onto the loop (0.4.104), and then removed entirely by the **full async rewrite in 0.7.0** — the integration now runs on an async SHC session, so there is no off-loop thread firing HA callbacks anymore.

Please update to the current release (**0.7.6**). Closing as fixed — reopen with a fresh log if you still see it on ≥0.7.x.
