### ISSUE TITLE
The integration is not loaded after Homeassisstant update

### ISSUE THREAD

**Issue by chini007** [tschamm/boschshc-hass#169]
Could you please help, below are the logs

![image](https://github.com/tschamm/boschshc-hass/assets/73479119/472edcf0-e517-4974-9c47-f56f3af83958)

**Logs**
Setup failed for custom integration bosch_shc: Unable to import component: Exception importing custom_components.bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bosch_shc/__init__.py", line 58, in <module>
    Platform.VALVE,
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: VALVE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 824, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.bosch_shc

**Comment by chini007** [comment]
Any update/help??? :(

**Comment by tschamm** [comment]
Please update to the latest HA version

**Comment by mosandlt** [comment]
Fixed and released in [v0.4.106](https://github.com/tschamm/boschshc-hass/releases/tag/v0.4.106): `Platform.VALVE` is now only registered when the running HA has it, so setup no longer fails on older HA. Please update and reopen if needed.

**Comment by mosandlt** [comment]
Fixed in **boschshc-hass 0.4.106** — the Platform.VALVE AttributeError on older HA was fixed.

Please update (via HACS, or manually — see #279) and restart Home Assistant. If you're on ≥0.4.106 and still hit this, comment here and we'll dig back in; otherwise I'll close this in ~2 weeks. Thanks!

**Comment by mosandlt** [comment]
The `Platform.VALVE` AttributeError on older HA was guarded (0.4.106).

Fixed in current releases — please update to **boschshc-hass 0.7.6**. Closing; reopen with a fresh log if it persists.
