### ISSUE TITLE
Exception 'PRE_ALARM' in the case of an intrusion alarm occurred

### ISSUE THREAD

**Issue by ThomasMatthes** [tschamm/boschshc-hass#170]
# Problem

If the intruder alarm is triggered, an exception occurs.

It seems that the alarm state `PRE_ALARM` is not considered in the implementation. Besides the exception, the availability of this additional alarm state would be very helpful for automations. 

It is unclear to me whether this can be realized in the SHC custom integration or whether this restriction is imposed by HA itself.

## Log message

```
2024-03-06 21:25:51.999 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bosch_shc/alarm_control_panel.py", line 106, in state
    if self._device.alarm_state == SHCIntrusionSystem.AlarmState.ALARM_ON:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/domain_impl.py", line 83, in alarm_state
    return self.AlarmState(self._raw_alarm_state["value"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'PRE_ALARM' is not a valid SHCIntrusionSystem.AlarmState
```

## Used versions

**HA**

* Core: 2024.2.5
* Supervisor: 2024.02.1
* Operating System: 12.0
* Frontend: 20240207.1

**SHC integration**

* SHC integration: 0.4.88

## Classification attempt

My assumption is that the pre-alarm is caused by the following settings:

![alarm01](https://github.com/tschamm/boschshc-hass/assets/152748546/088628eb-52f3-47c6-9403-955ca1427e22)![alarm02](https://github.com/tschamm/boschshc-hass/assets/152748546/4a804d78-d735-4b46-b4bb-71c7d8bb747b)

Based on the example configuration shown above, the silent pre-alarm could be triggered immediately after a sensor triggers at t==0s or after the alarm reminder time has elapsed at t==10s (depends on the implementation by Bosch).

## Solution

It would be nice to use a pre-alarm in HA automations to indicate via a notification or a signal light that the intrusion system has not yet been deactivated.

The question remains whether this issue could be taken into account in the SHC custom integration?

Thanks in advance!

**Comment by tschamm** [comment]
Will be fixed in the next release.
