### ISSUE TITLE
Roborock Integration stops working after boschshc-hass integration

### ISSUE THREAD

**Issue by GeilerGelber** [tschamm/boschshc-hass#182]
I integrated Bosch SHC on my Home Assistant.
Then I integrated Roborock, which was working without any problems.
Afterwards I installed this custom component, restarted HA and the new Devices like the Intrusion Detection System showed up in the list.
But now my Roborock integration isn't working anymore:
![image](https://github.com/tschamm/boschshc-hass/assets/31324031/7bc59de0-e876-47d2-8c00-3b0ed18bf8db)

I looked into the system logs, but no error logs for Roborock, but error logs for this custom component:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bosch_shc/switch.py:458
integration: Bosch SHC (documentation, issues)
First occurred: 20:57:56 (19 occurrences)
Last logged: 21:06:56

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1050, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1661, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bosch_shc/switch.py", line 458, in is_on
    getattr(self._device, self.entity_description.on_key)
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 452, in cameranotification
    return self._cameranotification_service.value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by GeilerGelber** [comment]
Problem seems to have solved itself, although I don't know why.
