### ISSUE TITLE
Error doing job ... Exception in callback

### ISSUE THREAD

**Issue by AlexW75** [tschamm/boschshc-hass#184]
Hello,

I occasionally encounter the following error...

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Quelle: custom_components/bosch_shc/sensor.py:371
Integration: Bosch SHC (Dokumentation, Probleme)
Erstmals aufgetreten: 10:39:06 (3 Vorkommnisse)
Zuletzt protokolliert: 10:39:16

Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in _async_write_ha_state_from_call_soon_threadsafe
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 543, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/sensor.py", line 371, in native_value
    return self._device.communicationquality.name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 35, in communicationquality
    return self._communicationquality_service.value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/services_impl.py", line 802, in value
    return self.State(self.state["quality"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'FETCHING' is not a valid CommunicationQualityService.State

**Comment by mosandlt** [comment]
Same thread-safety root cause — fixed by the async/marshalling changes in #300. Please verify the plug-firmware-update callback no longer raises after updating. Released in [v0.4.104](https://github.com/tschamm/boschshc-hass/releases/tag/v0.4.104) — OK to close once you've updated? Please reopen/comment if it persists.

**Comment by mosandlt** [comment]
Fixed in **boschshc-hass 0.4.104** — the CommunicationQuality / thread-safety crash was fixed.

Please update (via HACS, or manually — see #279) and restart Home Assistant. If you're on ≥0.4.104 and still hit this, comment here and we'll dig back in; otherwise I'll close this in ~2 weeks. Thanks!

**Comment by mosandlt** [comment]
This whole class of "called from a thread other than the event loop" / off-loop callback errors was fixed: first by marshalling the SHC polling-thread callbacks onto the loop (0.4.104), and then removed entirely by the **full async rewrite in 0.7.0** — the integration now runs on an async SHC session, so there is no off-loop thread firing HA callbacks anymore.

Please update to the current release (**0.7.6**). Closing as fixed — reopen with a fresh log if you still see it on ≥0.7.x.
