### ISSUE TITLE
Bosch-Smart-Home Controller

### ISSUE THREAD

**Issue by musicus07** [tschamm/boschshc-hass#187]
Whenever I open the Bosch Smart Home app on my Android 14 Pixel 4a5G cell phone,
I get this error message. 
What can I do?
Thank you very much

Immer wenn ich die Bosch-Smart-Home App in meinem Handy Android 14 Pixel 4a5G öffne,
bekomme ich diese Fehlermeldung. 
Was kann ich da tun?
Vielen Dank

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Quelle: custom_components/bosch_shc/switch.py:458
Integration: Bosch SHC (Dokumentation, Probleme)
Erstmals aufgetreten: 19:10:07 (3 Vorkommnisse)
Zuletzt protokolliert: 19:11:06

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1048, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1666, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bosch_shc/switch.py", line 458, in is_on
    getattr(self._device, self.entity_description.on_key)
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 452, in cameranotification
    return self._cameranotification_service.value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'`

**Comment by mosandlt** [comment]
Root cause confirmed and fixed: `cameranotification` (Camera 360) / `cameralight` (Camera Eyes) can return `None` before the service has been polled once, so reading `.value` raised the AttributeError. The switch now guards against the None service and reports "unavailable" until the first update.

The fix is queued for the next release — I'll follow up here when it ships.

**Comment by musikus70** [comment]
Vielen lieben Dank.
Großartige Arbeit die du hier leitest.

**Comment by mosandlt** [comment]
SHC 1 devices load correctly now — the `via_device` handling was fixed (0.4.96).

Fixed in current releases — please update to **boschshc-hass 0.7.6**. Closing; reopen with a fresh log if it persists.
