### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by moritzmaier84** [tschamm/boschshc-hass#188]
This one is showing up all day.

Logger: homeassistant
Quelle: custom_components/bosch_shc/switch.py:458
Integration: Bosch SHC ([Dokumentation](https://github.com/tschamm/boschshc-hass/blob/master/README.md), [Probleme](https://github.com/tschamm/boschshc-hass/issues))
Erstmals aufgetreten: 09:38:31 (17 Vorkommnisse)
Zuletzt protokolliert: 09:46:30

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1050, in _async_update_entity_states
await entity.async_update_ha_state(True)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1661, in state
if (is_on := self.is_on) is None:
^^^^^^^^^^
File "/config/custom_components/bosch_shc/switch.py", line 458, in is_on
getattr(self._device, self.entity_description.on_key)
File "/usr/local/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 452, in cameranotification
return self._cameranotification_service.value
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by mosandlt** [comment]
The "task exception was never retrieved" path is addressed by the thread-safety fixes in #300. Please verify after updating. Released in [v0.4.104](https://github.com/tschamm/boschshc-hass/releases/tag/v0.4.104) — OK to close once you've updated? Please reopen/comment if it persists.

**Comment by mosandlt** [comment]
Fixed in **boschshc-hass 0.4.104** — the camera-notification thread-safety crash was fixed.

Please update (via HACS, or manually — see #279) and restart Home Assistant. If you're on ≥0.4.104 and still hit this, comment here and we'll dig back in; otherwise I'll close this in ~2 weeks. Thanks!

**Comment by mosandlt** [comment]
This whole class of "called from a thread other than the event loop" / off-loop callback errors was fixed: first by marshalling the SHC polling-thread callbacks onto the loop (0.4.104), and then removed entirely by the **full async rewrite in 0.7.0** — the integration now runs on an async SHC session, so there is no off-loop thread firing HA callbacks anymore.

Please update to the current release (**0.7.6**). Closing as fixed — reopen with a fresh log if you still see it on ≥0.7.x.
