### ISSUE TITLE
Bug related to color temperature conversion

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#19]
There seems to be a bug in the conversion code for white temperatures (see log below). Seems that the color temperature cannot be gathered correctly?

Related: #17 

```
Logger: homeassistant.components.alexa.capabilities
Source: util/color.py:510
Integration: Amazon Alexa (documentation, issues)
First occurred: 7. Februar 2021, 20:08:32 (94 occurrences)
Last logged: 8:23:44

Unexpected error getting Alexa.ColorTemperatureController.colorTemperatureInKelvin property from <state light.stehlampe_mitte=on; min_mireds=153, max_mireds=500, brightness=255, color_temp=0, hs_color=(39.13, 54.118), rgb_color=(255, 206, 116), xy_color=(0.461, 0.412), friendly_name=Stehlampe mitte, supported_features=19 @ 2021-02-08T21:01:30.877374+01:00>
Unexpected error getting Alexa.ColorTemperatureController.colorTemperatureInKelvin property from <state light.gismo=on; min_mireds=153, max_mireds=500, brightness=255, color_temp=0, hs_color=(39.13, 54.118), rgb_color=(255, 206, 116), xy_color=(0.461, 0.412), entity_id=['light.stehlampe_oben', 'light.stehlampe_mitte'], friendly_name=Gismo, icon=mdi:lightbulb-group, supported_features=19 @ 2021-02-08T21:01:30.885542+01:00>
Unexpected error getting Alexa.ColorTemperatureController.colorTemperatureInKelvin property from <state light.stehlampe_mitte=on; min_mireds=153, max_mireds=500, brightness=255, color_temp=0, hs_color=(39.13, 54.118), rgb_color=(255, 206, 116), xy_color=(0.461, 0.412), friendly_name=Stehlampe mitte, supported_features=19 @ 2021-02-09T08:07:59.908412+01:00>
Unexpected error getting Alexa.ColorTemperatureController.colorTemperatureInKelvin property from <state light.gismo=on; min_mireds=153, max_mireds=500, brightness=255, color_temp=0, hs_color=(39.13, 54.118), rgb_color=(255, 206, 116), xy_color=(0.461, 0.412), entity_id=['light.stehlampe_oben', 'light.stehlampe_mitte'], friendly_name=Gismo, icon=mdi:lightbulb-group, supported_features=19 @ 2021-02-09T08:07:59.916410+01:00>
Unexpected error getting Alexa.ColorTemperatureController.colorTemperatureInKelvin property from <state light.stehlampe_oben=on; min_mireds=153, max_mireds=500, brightness=255, color_temp=0, hs_color=(39.13, 54.118), rgb_color=(255, 206, 116), xy_color=(0.461, 0.412), friendly_name=Stehlampe oben, supported_features=19 @ 2021-02-09T08:08:08.121837+01:00>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 243, in serialize_properties
    prop_value = self.get_property(prop_name)
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 624, in get_property
    return color_util.color_temperature_mired_to_kelvin(
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 510, in color_temperature_mired_to_kelvin
    return math.floor(1000000 / mired_temperature)
ZeroDivisionError: division by zero
```

**Comment by tschamm** [comment]
The integration returned 0 if the device does not provide a color temp. I'm wondering what would be correct? We may return either `None` or a color temperature derived from an rgb value. However, this mapping is not defined AFAIK.

**Comment by JanZimmer** [comment]
Aren’t the conversion functions reversible in some kind of way (or are there any precision errors)?

**Comment by tschamm** [comment]
At least I'm not aware of any function implemented in HA doing this. There are some solutions described how to map an xy-color space to color temp, or some approaches using [lookup tables](https://andi-siess.de/rgb-to-color-temperature/) but I do not prefer to have this integration calculate this in some magic way.

Can you report how it behaves when `None` is returned?

**Comment by tschamm** [comment]
After a quick test, `color_temp` property is not reported in the `states_attributes` anymore. The `hue` integration also ignores the conversion from `rgb` to `color_temp`. I hope it's fine for you to close the issue. 
Otherwise please reopen, if you are aware of a transformation.
