### ISSUE TITLE
Check whether temperature is settable on room climate, before setting it

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#20]
This is not really a big issue, but before setting a temperature on a room climate, one should ensure that the room climate is not in 'Lo' mode (window open). Otherwise, setting the temperature anyways will result in an error in the logs.

```
2021-02-09 03:00:00 ERROR (SyncWorker_7) [root] Body: {"@type": "climateControlState", "setpointTemperature": 14.0}
2021-02-09 03:00:00 ERROR (SyncWorker_7) [root] Headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'api-version': '2.1', 'Content-Type': 'application/json', 'Content-Length': '61'}
2021-02-09 03:00:00 ERROR (SyncWorker_7) [root] URL: https://192.168.178.64:8444/smarthome/devices/roomClimateControl_hz_6/services/RoomClimateControl/state
2021-02-09 03:00:01 ERROR (MainThread) [homeassistant.components.automation.neue_automatisierung] Reset Climate: Error executing script. Unexpected error for call_service at pos 2: API call returned non-OK result (code 400)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"WRONG_THERMOSTAT_GROUP_MODE","statusCode":400}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
await entity.async_set_temperature(**kwargs)
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 404, in async_set_temperature
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/bosch_shc/climate.py", line 163, in set_temperature
self._device.setpoint_temperature = float(temperature)
File "/usr/local/lib/python3.8/site-packages/boschshcpy/models_impl.py", line 335, in setpoint_temperature
self._roomclimatecontrol_service.setpoint_temperature = temperature
File "/usr/local/lib/python3.8/site-packages/boschshcpy/services_impl.py", line 45, in setpoint_temperature
self.put_state_element("setpointTemperature", value)
File "/usr/local/lib/python3.8/site-packages/boschshcpy/device_service.py", line 47, in put_state_element
self.put_state({key: value})
File "/usr/local/lib/python3.8/site-packages/boschshcpy/device_service.py", line 42, in put_state
self._api.put_device_service_state(
File "/usr/local/lib/python3.8/site-packages/boschshcpy/api.py", line 142, in put_device_service_state
self._put_api_or_fail(api_url, state_update)
File "/usr/local/lib/python3.8/site-packages/boschshcpy/api.py", line 82, in _put_api_or_fail
self._process_nok_result(result)
File "/usr/local/lib/python3.8/site-packages/boschshcpy/api.py", line 101, in _process_nok_result
raise ValueError(
ValueError: API call returned non-OK result (code 400)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"WRONG_THERMOSTAT_GROUP_MODE","statusCode":400}'
```

**Comment by tschamm** [comment]
Thanks for reporting. I did not test this in my installation, so please reopen, if this fix does not work for you.

**Comment by endsideX** [comment]
Thank you for the great integration.

Unfortunately, I observe the same phenomenon as JanZimmer. When the windows are open and I operate the thermostats I get the error :

2021-04-29 11:29:59 ERROR (SyncWorker_3) [root] Body: {"@type": "climateControlState", "setpointTemperature": 5.0}
2021-04-29 11:29:59 ERROR (SyncWorker_3) [root] Headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'api-version': '2.1', 'Content-Type': 'application/json', 'Content-Length': '60'}
2021-04-29 11:29:59 ERROR (SyncWorker_3) [root] URL: https://192.168.178.36:8444/smarthome/devices/roomClimateControl_hz_5/services/RoomClimateControl/state
2021-04-29 11:29:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1846305072] API call returned non-OK result (code 400)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"WRONG_THERMOSTAT_GROUP_MODE","statusCode":400}'


I use the current version of the inegration.

**Comment by tschamm** [comment]
I confirm the phenomen, I guess this only happens after you reset the room climate control mode to AUTOMATIC mode. I reported this as a bug in the Room Climate Control behavior within the SHC system: https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/51
