### ISSUE TITLE
Issues with Camera_360

### ISSUE THREAD

**Issue by sirtux** [tschamm/boschshc-hass#206]
Hi,

when using a camera360 in HA,
I get the following error:

```
2024-11-25 15:08:39.900 ERROR (MainThread) [homeassistant.components.switch] Error adding entity switch.tomcam_notification for domain switch with platform bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1672, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bosch_shc/switch.py", line 458, in is_on
    getattr(self._device, self.entity_description.on_key)
  File "/config/deps/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 452, in cameranotification
    return self._cameranotification_service.value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

This is with HA 2024.11.3, and boschshc-hass 0.4.92.

Thanks for your hard work on this great integration!

**Comment by tschamm** [comment]
Do you still see the notification service in the Bosch (Smart Home) app? It seems Bosch Camera App is not providing this service anymore to Bosch Smart Home app. I have the same at my home, seems I need to remove the service as this is unreliable.

**Comment by mosandlt** [comment]
Fixed and released in [v0.4.105](https://github.com/tschamm/boschshc-hass/releases/tag/v0.4.105). The camera 360 privacy/notification switches no longer crash on toggle (None-service guard). Please update via HACS and reopen if it still occurs.

**Comment by mosandlt** [comment]
Fixed in **boschshc-hass 0.4.105** — the Camera 360 None-guard crash was fixed.

Please update (via HACS, or manually — see #279) and restart Home Assistant. If you're on ≥0.4.105 and still hit this, comment here and we'll dig back in; otherwise I'll close this in ~2 weeks. Thanks!

**Comment by mosandlt** [comment]
Camera 360 no longer crashes — a None-guard was added on the camera notification service (0.4.105).

Fixed in current releases — please update to **boschshc-hass 0.7.6**. Closing; reopen with a fresh log if it persists.
