### ISSUE TITLE
Intrusion Detection System not supported anymore

### ISSUE THREAD

**Issue by pabera** [tschamm/boschshc-hass#212]
Since the most recent update of Home Assistant, the entity of Intrusion Detection System is not available anymore. Here are some logs I could find. Bosch also had a few updates recently, maybe they changed the names of the attributes?!

```
Logger: homeassistant
Quelle: custom_components/bosch_shc/alarm_control_panel.py:102
Integration: Bosch SHC ([Dokumentation](https://github.com/tschamm/boschshc-hass/blob/master/README.md), [Probleme](https://github.com/tschamm/boschshc-hass/issues))
Erstmals aufgetreten: 11. Dezember 2024 um 13:40:19 (190 Vorkommnisse)
Zuletzt protokolliert: 05:59:00

Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1014, in _async_write_ha_state_from_call_soon_threadsafe
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 219, in state
    if (alarm_state := self.alarm_state) is not None:
                       ^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/alarm_control_panel.py", line 102, in alarm_state
    if self._device.alarm_state == SHCIntrusionSystem.AlarmState.PRE_ALARM:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AlarmState' has no attribute 'PRE_ALARM'
```

```
Logger: homeassistant.components.alarm_control_panel
Quelle: helpers/entity_platform.py:608
Integration: Alarmzentrale ([Dokumentation](https://www.home-assistant.io/integrations/alarm_control_panel), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
Erstmals aufgetreten: 11. Dezember 2024 um 09:58:09 (2 Vorkommnisse)
Zuletzt protokolliert: 08:23:49

Error adding entity alarm_control_panel.intrusion_detection_system for domain alarm_control_panel with platform bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 219, in state
    if (alarm_state := self.alarm_state) is not None:
                       ^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/alarm_control_panel.py", line 102, in alarm_state
    if self._device.alarm_state == SHCIntrusionSystem.AlarmState.PRE_ALARM:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AlarmState' has no attribute 'PRE_ALARM'
```

**Comment by pabera** [comment]
I was able to get rid of the error by restarting HA. I am not sure how the system ended up in this state.
