### ISSUE TITLE
Integration not working after latest bosch smarthome controller update.

### ISSUE THREAD

**Issue by cars1806** [tschamm/boschshc-hass#32]
Hello,

since I updated my bsc to the newest firmware (10.2.2164-20551) the shutter controls are not working anymore.
The climate control and contact sensors are working as normal.
I get the following error logs when trying to control my shutters:

2021-09-04 19:36:00 ERROR (SyncWorker_3) [root] Body: {"@type": "shutterControlState", "level": 0.0}
2021-09-04 19:36:00 ERROR (SyncWorker_3) [root] Headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'api-version': '2.1', 'Content-Type': 'application/json', 'Content-Length': '46'}
2021-09-04 19:36:00 ERROR (SyncWorker_3) [root] URL: https://169.254.65.242:8444/smarthome/devices/hdm:HomeMaticIP:3014F711A00018DBB85E66A4/services/ShutterControl/state
2021-09-04 19:36:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547964644368] SHC Error (message: API call returned non-OK result (code 503)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"SERVICE_INVOCATION_FAILED","statusCode":503}')
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 288, in async_close_cover
await self.hass.async_add_executor_job(ft.partial(self.close_cover, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/bosch_shc/cover.py", line 89, in close_cover
self._device.level = 0.0
File "/usr/local/lib/python3.9/site-packages/boschshcpy/models_impl.py", line 182, in level
self._service.put_state_element("level", level)
File "/usr/local/lib/python3.9/site-packages/boschshcpy/device_service.py", line 49, in put_state_element
self.put_state({key: value})
File "/usr/local/lib/python3.9/site-packages/boschshcpy/device_service.py", line 44, in put_state
self._api.put_device_service_state(
File "/usr/local/lib/python3.9/site-packages/boschshcpy/api.py", line 170, in put_device_service_state
self._put_api_or_fail(api_url, state_update)
File "/usr/local/lib/python3.9/site-packages/boschshcpy/api.py", line 102, in _put_api_or_fail
self._process_nok_result(result)
File "/usr/local/lib/python3.9/site-packages/boschshcpy/api.py", line 123, in _process_nok_result
raise SHCSessionError(
boschshcpy.exceptions.SHCSessionError: SHC Error (message: API call returned non-OK result (code 503)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"SERVICE_INVOCATION_FAILED","statusCode":503}')

Sorry for bad formatting, i could not find how to properly format log entries on github.

**Comment by tschamm** [comment]
I have the same firmware running and have no problems when opening/closing the covers. Did you try to restart Home Assistant?

**Comment by JanZimmer** [comment]
I am experiencing another bug after the same update.

Somehow, the integration changed the IP of the SHC to 169.XX.XX.XX and refuses to automatically change it back.

**Comment by cars1806** [comment]
Sorry for the late reply. 
So I did restart the system several times with no luck.

But what I noticed now is the following: Everything works normal if I control the shutters with my hue dimmer switch (connected directly to HA with a zigbee stick). But as soon as I try to control it via HA UI, I get this error messages and I can't control it anymore with the hue switch either for a period of time (not sure how long). 

Not sure if there's anything you can do about that now and it isn't really a problem for me at the moment if I can control with my hardware switches. So for me it would be ok to close this issue until someone really needs a fix for this.

**Comment by cars1806** [comment]
What I wanted to add, as you can see in my original error logs I got the same issues as @JanZimmer. Theres also this 169.XXX.XXX.XXX ip-address and also the Error 503 he mentioned in another thread. 

I have a hard time to explain all that stuff in Englisch, if you need some more explanation and information about the issue, maybe I can better assist you in german if that's possible in some way here.

**Comment by tschamm** [comment]
Thanks for your comments. I observed the IP change once in my setting, but I don't have a clue if the reason is on HA side, zeroconf or anything else.
@cars1806 Thanks for pointing out the IP, I didn't see this in your first comment. Hopefully this is the reason for the strange behavior.

**Comment by cars1806** [comment]
Todays update did not change anything, but I deleted the integration and reconfigured it. Now it works perfectly again. Should have tried that before. I was worried I could lose my automations. But thankfully that's not how HA works. Sorry for the inconvenience.

But thank you so much for your work!
