### ISSUE TITLE
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'

### ISSUE THREAD

**Issue by schreierc84** [tschamm/boschshc-hass#41]
Thank you for providing the Bosch Smart Home Integration. I'm looking forward to use it. But I'm facing an issue after installation.

After installation as described in https://github.com/tschamm/boschshc-hass#readme I've restarted Home Assistant. Now I see following error in the logs:
```
2021-12-11 08:11:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 170, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
integration.get_platform("config_flow")
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/bosch_shc/config_flow.py", line 78, in <module>
class ConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
File "/config/custom_components/bosch_shc/config_flow.py", line 186, in ConfigFlow
self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'
```

I'm running Home Assistant 2021.11.5

**Comment by tschamm** [comment]
The version you are using is a pre-release, working only with the current 2021.12 beta. Please install either the component in 0.4.18 or use the current beta of home assistant.

**Comment by schreierc84** [comment]
Thank you, @tschamm!
I'm new to GitHub, is there a better way to ask such maybe stupid questions where the bug is in front of the computer :) ?

**Comment by tschamm** [comment]
All fine. But there is also a forum on [home-assistant.io](https://community.home-assistant.io/t/bosch-smart-home/115864/257)
