### ISSUE TITLE
KeyError: 'smokeDetectionSystem'

### ISSUE THREAD

**Issue by endsideX** [tschamm/boschshc-hass#51]
Unfortunately I have a problem in my Bosch integration since the last update. Various entities are displayed as unavailable.
In the logs I find the following entry, which apparently cancels the correct integration.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bosch_shc/binary_sensor.py", line 81, in async_setup_entry
    binary_sensor = session.device_helper.smoke_detection_system
  File "/usr/local/lib/python3.9/site-packages/boschshcpy/device_helper.py", line 182, in smoke_detection_system
    return self._devices_by_model["SMOKE_DETECTION_SYSTEM"]["smokeDetectionSystem"]
KeyError: 'smokeDetectionSystem'`

It would be nice if you could help me.

**Comment by tschamm** [comment]
That's strange, but in line with others reporting issues with the new release. 
Can you please try a restart and report if the issue still exists?
