### ISSUE TITLE
Error adding entities for domain light with platform bosch_shc

### ISSUE THREAD

**Issue by wsirhc** [tschamm/boschshc-hass#8]
I did install the branch into my custom-components folder from scratch. So due to initializing the boschshc-devices, the following error occurs in HA-Logs. Thus the lights will not be added as entity.

```

Logger: homeassistant.components.light
Source: custom_components/bosch_shc/light.py:40
Integration: Licht (documentation, issues)
First occurred: 08:36:14 (8 occurrences)
Last logged: 08:39:15

    Error adding entities for domain light with platform bosch_shc
    Error while setting up bosch_shc platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 412, in capability_attributes
    supported_features = self.supported_features
  File "/config/custom_components/bosch_shc/light.py", line 40, in supported_features
    if self._device.supports_brightness:
AttributeError: 'SHCLight' object has no attribute 'supports_brightness'


```

**Comment by tschamm** [comment]
I forgot to update the version in manifest.json. Should be fixed with f6dd8f3.
