### ISSUE TITLE
"Unable to install package boschshcpy==0.2.52"

### ISSUE THREAD

**Issue by dolodobendan** [tschamm/boschshc-hass#83]
The updater fails on my NUC (ubuntu server, HA installed as snap):

```
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 2:42:15 PM (3 occurrences)
Last logged: 2:42:18 PM

Unable to install package boschshcpy==0.2.52: ERROR: Will not install to the user site because it will lack sys.path precedence to boschshcpy in /snap/home-assistant-snap/547/lib/python3.10/site-packages
```

Version:

![image](https://user-images.githubusercontent.com/37902856/215777955-ed8ea042-123a-4c6a-9d94-22c034762532.png)

Not sure if I should've posted this in boschshcpy...

**Comment by tschamm** [comment]
Hi @dolodobendan,
what is the last boschshcpy version installed in your site-packages folder? I have not observed that kind of message yet, but maybe it is related with some updated I did recently to the boschshcpy package providing some executable scripts.

**Comment by dolodobendan** [comment]
Hi @tschamm! Does this help?

![image](https://user-images.githubusercontent.com/37902856/215891434-dc694e28-a9e0-4ab7-add9-803bd340434a.png)

![image](https://user-images.githubusercontent.com/37902856/215890916-bc45f32f-2bc1-4b29-97f4-1c3e9ee27db6.png)

"current" symlinks to "533" which isn't there.

**Comment by tschamm** [comment]
Can you check whether the error is persistent? I'll released a new version of boschshcpy, maybe the error is gone now.

**Comment by dolodobendan** [comment]
Thank you for looking into it. It's still there:

![image](https://user-images.githubusercontent.com/37902856/219968154-e57df83a-6359-4744-9e79-e73c17f68447.png)

Maybe this pip-thingy has something to do with it? That's new, I think.

**Comment by dolodobendan** [comment]
I thought I gave it another try. I uninstalled both the HACS version and then the regular version of this integration and did a reboot. Then I installed the HACS version and rebooted again. Then I installed the regular version (was it always like this?) - or better, I tried:

![image](https://user-images.githubusercontent.com/37902856/224543579-1ad28994-0571-459b-a993-f22a5f45e82d.png)

Log overview:

![image](https://user-images.githubusercontent.com/37902856/224543607-1bfeb99f-505e-4893-9b23-cb0a0c4c65d3.png)

```
Logger: homeassistant
Source: requirements.py:290
First occurred: 12:53:51 PM (1 occurrences)
Last logged: 12:53:51 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/helpers/discovery_flow.py", line 71, in _async_start
    await gather_with_concurrency(
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/util/async_.py", line 201, in gather_with_concurrency
    return await gather(
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/util/async_.py", line 199, in sem_task
    return await task
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/config_entries.py", line 798, in async_init
    flow, result = await task
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/config_entries.py", line 816, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/config_entries.py", line 922, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/setup.py", line 384, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/requirements.py", line 290, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for bosch_shc not found: ['boschshcpy==0.2.56'].
```

```
Logger: aiohttp.server
Source: requirements.py:163
First occurred: 12:53:51 PM (1 occurrences)
Last logged: 12:53:51 PM

Error handling request
Traceback (most recent call last):
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/config_entries.py", line 798, in async_init
    flow, result = await task
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/config_entries.py", line 816, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/config_entries.py", line 922, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/setup.py", line 384, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/snap/home-assistant-snap/555/lib/python3.10/site-packages/homeassistant/requirements.py", line 163, in async_get_integration_with_requirements
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'bosch_shc' not found.

```

```
Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 12:53:48 PM (3 occurrences)
Last logged: 12:53:51 PM

Unable to install package boschshcpy==0.2.56: ERROR: Will not install to the user site because it will lack sys.path precedence to boschshcpy in /snap/home-assistant-snap/555/lib/python3.10/site-packages [notice] A new release of pip available: 22.3.1 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
```

Same thing after a reboot.

**Comment by tschamm** [comment]
I guess this is outdated, so I close it

**Comment by dolodobendan** [comment]
It's not, but it's my test system, so nothing urgent. I assume it has something to do with it being a snap installation as I have no problems with other types of installation.. I don't see this with other integrations, however.
